vich_uploader:
    db_driver: orm

    mappings: 
        pieces_jointes:
            uri_prefix: /images/piecesJointes
            upload_destination: '%kernel.project_dir%/public/images/piecesJointes'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
